### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by mloubout** [JuliaMath/Polynomials.jl#248] opened 2020-08-04 19:27 UTC
Hello, as of this morning, `Polynomials` seems to be broken and I cannot compile and use may packages depending on it anymore

```
 pkg> add Polynomials
 Resolving package versions...
  Updating `/JOLI.jl/Project.toml`
  [f27b6e38] + Polynomials v1.1.3
  Updating `/JOLI.jl/Manifest.toml`
 [no changes]

julia> using Polynomials
[ Info: Precompiling Polynomials [f27b6e38-b328-58d1-80ce-0feddd5e7a45]
ERROR: LoadError: ArgumentError: Package Polynomials does not have OffsetArrays in its dependencies:
- If you have Polynomials checked out for development and have
  added OffsetArrays as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Polynomials

```

This is in a fresh system with nothing else installed.

**Comment by jverzani** [comment] 2020-08-04 19:47
Shoot, sorry. I just added that dependency and thought it was all set up. Thanks for reporting. I'll try and push a fix ASAP.

**Comment by jverzani** [comment] 2020-08-04 19:48
This should only impact the master release. In the interim you could follow the last tagged release.

**Comment by mloubout** [comment] 2020-08-04 19:56
Thank you for the quick answer. THe issue seems to have magically disappeared (was installing just via the normal `] add Polynomials` so was supposed to get latest tagged release. I'm gonna assume there was some sync issue with the julia registry and it was picking up the wrong version.

It is still an issue on master indeed though, but up to you if you want to close this  one.

**Comment by jverzani** [comment] 2020-08-04 19:59
Well, that is interesting.

I tried replicating the error with and without master on a newly activated directory and can't replicate the issue. Admittedly, I'm a bit confused as to the cause, as  I thought I had added OffsetArrays properly. 

I'm glad it is working for you now, and will see if I can identify what is going on with master. I'll leave this open until then.

Thanks again for the report!

**Comment by mloubout** [comment] 2020-08-04 20:09
> Admittedly, I'm a bit confused as to the cause, as I thought I had added OffsetArrays properly.

Every looks proper indeed, and now master magically works too. I have zero idea what happened except some weird github miss maybe???

just to be clear I literally ran

```
docker run julia:1.3
]add Polynomials
using Polynomials
```
Errored, quit the docker and restart and was working, so 99% sure now that probably not an issue on your side.

Cheers, and thanks again for quick reply.

**Comment by jverzani** [comment] 2020-08-04 20:11
Thanks for this last comment. I'll close this for now and hope it doesn't come back. I just clicked through a bit to follow the linked issue, but your project looks very impressive!

**Closed by jverzani** 2020-08-04 20:11 UTC

**Comment by jakebolewski** [comment] 2020-08-04 20:40
@jverzani I don't think it was your fault but thanks for fixing it :)

See https://github.com/JuliaLang/Pkg.jl/issues/1942

**Comment by mloubout** [comment] 2020-08-04 20:43
@jakebolewski thanks for the link, and also ouch looks nasty, explains why it suddenly switched to these `Github.com` log that fixed it.
